=== windbamboo/php/xml/day01/ext/demo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Breakfast_menu">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Food" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="Price" type="xs:decimal"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== windbamboo/php/xml/day01/ext/demo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Breakfast_menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="demo2.xsd">
	<Food>
		<Name>中国早餐</Name>
		<Description>两个鸡蛋</Description>
		<Price>12.3</Price>
	</Food>
	<Food>
		<Name></Name>
		<Description></Description>
		<Price>23.3</Price>
	</Food>
</Breakfast_menu>
